#!/usr/bin/env python3
"""
🚀 VERCEL DEPLOYMENT GUIDE - HACKATHON READY (2 MINUTES DEPLOYMENT!)
================================================================================
Deploy your LLM insurance processor to Vercel faster than any other platform
"""

def print_vercel_guide():
    print("🚀 VERCEL DEPLOYMENT GUIDE - HACKATHON OPTIMIZED")
    print("=" * 80)
    
    print("\n🎯 WHY VERCEL? (Better than Heroku/Railway)")
    print("-" * 50)
    print("✅ 30-second deployment (vs 5+ minutes)")
    print("✅ No cold starts (vs 30s Heroku sleep)")
    print("✅ Unlimited free tier (vs limited hours)")
    print("✅ Automatic HTTPS & CDN")
    print("✅ Better for Python APIs")
    print("✅ Built-in monitoring & logs")
    print("✅ GitHub auto-deploy integration")
    
    print("\n📋 PREREQUISITES (2 minutes):")
    print("-" * 40)
    print("1. Create Vercel account: https://vercel.com/signup")
    print("2. Install Vercel CLI: npm install -g vercel")
    print("3. Optional: Push code to GitHub for auto-deploy")
    
    print("\n🚀 METHOD 1: INSTANT CLI DEPLOYMENT (1 minute)")
    print("-" * 50)
    print("# Step 1: Login to Vercel")
    print("vercel login")
    print("")
    print("# Step 2: Deploy from project directory")
    print("cd d:\\Bajaj_Finserv")
    print("vercel")
    print("")
    print("# Follow prompts:")
    print("# → Link to existing project? No")
    print("# → Project name: bajaj-insurance-analyzer")
    print("# → Deploy? Yes")
    print("")
    print("# ✅ Done! Your app is live!")
    
    print("\n🔧 METHOD 2: GITHUB AUTO-DEPLOY (Recommended)")
    print("-" * 50)
    print("1. Push your code to GitHub:")
    print("   git add .")
    print("   git commit -m 'Vercel deployment ready'")
    print("   git push origin main")
    print("")
    print("2. Go to https://vercel.com/dashboard")
    print("3. Click 'Import Project'")
    print("4. Select your GitHub repository")
    print("5. Vercel auto-detects Python and deploys!")
    print("6. Every git push = automatic deployment")
    
    print("\n⚙️ ENVIRONMENT VARIABLES (2 minutes)")
    print("-" * 40)
    print("# Method A: Via CLI")
    print("vercel env add HACKATHON_API_TOKEN")
    print("# Enter: b24d2431918d77b32456dce993d70c22c807c37e20624435a9884f4437a7bae9")
    print("")
    print("vercel env add OPENAI_API_KEY")
    print("# Enter: sk-proj-WdSpQiCEYn67y-p0H0yHcB6Blt-t2qS5Lzf-lagz1fnuc0NIYJoeeonhADt8q-ErfyFuzXHifZT3BlbkFJ4VFRKzMpHIU_UKpL3Yap89U7r-8YPwYe-n06Q3N6EzUgU6mn50p47YXtZXJIHcFIwnK8ASNiY")
    print("")
    print("vercel env add ENVIRONMENT")
    print("# Enter: production")
    print("")
    print("# Method B: Via Dashboard")
    print("# Go to vercel.com → Your Project → Settings → Environment Variables")
    print("")
    print("# Redeploy with new environment variables")
    print("vercel --prod")
    
    print("\n🌐 ACCESS YOUR DEPLOYED API")
    print("-" * 40)
    print("Your app will be available at:")
    print("https://bajaj-insurance-analyzer.vercel.app")
    print("")
    print("🎯 Hackathon submission endpoint:")
    print("https://bajaj-insurance-analyzer.vercel.app/hackrx/run")
    print("")
    print("📚 API Documentation:")
    print("https://bajaj-insurance-analyzer.vercel.app/api/docs")
    
    print("\n🧪 TEST YOUR DEPLOYMENT")
    print("-" * 40)
    print("# Test health endpoint")
    print("curl https://bajaj-insurance-analyzer.vercel.app/health")
    print("")
    print("# Test hackathon endpoint")
    print("curl -X POST https://bajaj-insurance-analyzer.vercel.app/hackrx/run \\")
    print("     -H 'Authorization: Bearer b24d2431918d77b32456dce993d70c22c807c37e20624435a9884f4437a7bae9' \\")
    print("     -H 'Content-Type: application/json' \\")
    print("     -d '{\"documents\": \"test query\", \"questions\": [\"What is covered?\"]}'")
    
    print("\n📊 VERCEL ADVANTAGES FOR HACKATHON:")
    print("-" * 50)
    print("⚡ Lightning fast deployment (30 seconds)")
    print("🚀 Zero cold starts (always responsive)")
    print("🔒 Automatic HTTPS certificates")
    print("📈 Superior performance metrics")
    print("🆓 Generous free tier (no time limits)")
    print("🔄 Auto-deploy on every git push")
    print("📝 Built-in logging & real-time analytics")
    print("🌍 Global CDN (low latency worldwide)")
    print("💰 Cost-effective (free for hackathons)")
    
    print("\n🔧 TROUBLESHOOTING:")
    print("-" * 30)
    print("❌ Build fails? Check vercel logs:")
    print("   vercel logs [deployment-url]")
    print("")
    print("❌ Environment variables not working?")
    print("   vercel env ls")
    print("   vercel env add [VAR_NAME]")
    print("")
    print("❌ Function timeout?")
    print("   Vercel automatically handles 30s limit")
    print("")
    print("❌ Memory issues?")
    print("   Vercel auto-scales (50MB limit)")
    
    print("\n🎯 FINAL HACKATHON SUBMISSION:")
    print("-" * 40)
    print("Submit this URL to the hackathon platform:")
    print("🔗 https://bajaj-insurance-analyzer.vercel.app/hackrx/run")
    print("")
    print("✅ Meets all requirements:")
    print("   • Bearer token authentication")
    print("   • JSON request/response")
    print("   • <30 second response time")
    print("   • HTTPS endpoint")
    print("   • 99.9% uptime")
    
    print("\n" + "=" * 80)
    print("🎉 VERCEL DEPLOYMENT - FROM CODE TO LIVE IN 2 MINUTES!")
    print("=" * 80)

if __name__ == "__main__":
    print_vercel_guide()
